### ISSUE TITLE
After a few steps I encounter an error on my terminal.

### ISSUE THREAD

**Issue by Pigorous** [ychalier/hoplite#3]
Traceback (most recent call last):
File "/home/hoplite/main.py", line 3, in <module>
    import hoplite.__main__
  File "/home/hoplite/hoplite/__main__.py", line 243, in <module>
    main()
  File "/home/hoplite/hoplite/__main__.py", line 236, in main
    play(args.serial, args.prayers, args.record)
  File "/home/hoplite/hoplite/__main__.py", line 87, in play
    controller.run()
  File "/home/hoplite/hoplite/controller.py", line 192, in run
    self.step()
  File "/home/hoplite/hoplite/controller.py", line 155, in step
    move = self.brain.pick_move(self.memory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hoplite/hoplite/brain.py", line 172, in pick_move
    best_move = max(outcomes.items(), key=lambda x: x[1])[0]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: max() arg is an empty sequence

**Comment by ychalier** [comment]
Hey,

That happens when the script thinks it has no available move, which should not happen during the game? So I would say this results from screen observation errors. Check that:

1. you're using a phone with a screen resolution of 1080*1920 (or edit observation functions accordingly) and
2. classifier tolerance is high enough (as in the `classifier-tempfix` branch).

Even with that, there will still be errors until classifiers are fixed (see `classifier-tempfix` README). For troubleshooting, you may save screenshots of the game with the `-r` flag, and later check what the script thinks it sees with the `check` action.
